### ISSUE TITLE
passed wrong type to binary()

### ISSUE THREAD

**Issue by colorcube** [dy/subscript#17]
My IDE might have found an error:

https://github.com/dy/subscript/blob/098f480fe5a87d21a030b0ef084c57423b0125ec/subscript.js#L19

the third parameter expects a number:

https://github.com/dy/subscript/blob/098f480fe5a87d21a030b0ef084c57423b0125ec/parse.js#L81

**Comment by dy** [comment]
yeah, IDEs are not very comprehensive. It's not an error, it's intentional
