### ISSUE TITLE
We need to convert the tree into a formula. Can you support it?

### ISSUE THREAD

**Issue by YangJunNan** [dy/subscript#20]
We need to convert the tree into a formula. Can you support it?

**Comment by dy** [comment]
What formula do you mean, math? It is possible for sure, but I don't have premade solution, you'd need to do it yourself. It must be easy though.

**Comment by YangJunNan** [comment]
Will it be supported in the future?

**Comment by dy** [comment]
Can you give example what formula do you expect?

**Comment by YangJunNan** [comment]
```
const exp1 = `a + b * c`
const b = `(e + f)`
```

We can use AST to calculate value.
And we  need to record the replaced expression  `a + (e +f ) * c`.

**Comment by dy** [comment]
Got you. I've added codegenerator in subscript v9. Now you can use it as

```js
import {stringify} from 'subscript'

stringify(['+', 'a', 'b']) // "a + b"
```

Please let me know if it helps.

**Comment by YangJunNan** [comment]
It's helpful to us.
Thank you very much!
