### ISSUE TITLE
stringify function have a problem

### ISSUE THREAD

**Issue by YangJunNan** [dy/subscript#21]
```
const neeTree = ['+', 0 , 1]
console.log("stringify", stringify(neeTree))

````

result
![image](https://github.com/user-attachments/assets/3b129ae1-bcf0-454d-90a1-c04c166e9c4a)

**Comment by YangJunNan** [comment]
```
const neeTree1 = ['+', 0 , 1]
console.log('-------stringify 1----------')
console.log(stringify(neeTree1))

const neeTree2 = ['+', false , 1]
console.log('-------stringify 2----------')
console.log(stringify(neeTree2))
```

![image](https://github.com/user-attachments/assets/aa186b61-5207-44d9-a722-6b59f6c84050)

**Comment by dy** [comment]
To stringify primitives, wrap them in a node like that: ['+', [,0], [,1]]. Because direct values are for ids/vars. Pls let me know if it works.

**Comment by YangJunNan** [comment]
![image](https://github.com/user-attachments/assets/d0cdf1dd-2160-4286-bf8a-96ea74c09893)

![image](https://github.com/user-attachments/assets/d84eed84-418a-403f-abb8-e6e2a2fc462c)

It works.
I need to know exactly how many characters are like this.
The characters I confirmed include the number 0 and Boolean values.

README.md need be updated  in response to this situation.

Thank you.

**Comment by dy** [comment]
But it's covered in readme, under [syntax tree](https://github.com/dy/subscript/blob/main/README.md#syntax-tree) section.  
Please let me know what or how would you like it covered, what is not clear from that.

The logic is the following: if you see direct primitive, like `['+', 1, 'a', false]` - consider it `scope[1] + scope['a'] + scope[false]`. Normally you expect to see only strings or null/undefined for missing argument.
If you see wrapped primitive, like `['+', [,1], [,'a'], [,false]]` - consider that literal value `1 + '2' + false`.
